version: '3'

services:
  nginx:
    build: ./nginx
    container_name: nginx
    networks: 
      - node-network
    ports: 
      - "8080:80"
    depends_on:
      app:
        condition: service_healthy

  app:
    build: ./node
    container_name: app
    entrypoint: wait-for db:3306 -t 40 -- sh -c 'npm install && npm start'
    networks: 
      - node-network
    volumes:
      - ./node:/usr/src/app
    healthcheck:
      test: curl --fail http://localhost:3000
      interval: 10s
      timeout: 15s
      retries: 5
      start_period: 10s
    depends_on:
      - db

  db:
    image: mysql:5.7
    platform: linux/x86_64
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge
